### ISSUE TITLE
Connect error (2002) no such file or directory

### ISSUE THREAD

**Issue by Famku** [christianreiss/al-youphptube#1]
Hi, I try to use your youPHPtube docker version.

I am able to open the the config site, but get the error message"  Connect error (2002) no such file or directory"

Can you please tell me what I have to enter here?

regards

**Comment by christianreiss** [comment]
Hey,
sorry for taking a while-- I was busy in real life.
The error you describe occurs when you configure the system and leave "Localhost" as the MySQL Server. You need to point it to an existing mysql server.

**Comment by Famku** [comment]
Thanks, I thought the database is also in docker.
I will test it.
